# Generated by Django 4.1.7 on 2023-09-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="redeem_link",
            field=models.URLField(null=True),
        ),
    ]
