# Generated by Django 4.1.7 on 2023-09-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_alter_paymentrequest_amount_awarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="status",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
