# Generated by Django 4.1.7 on 2023-09-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_bank_momocode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
